### ISSUE TITLE
Won't inline urls from css properties

### ISSUE THREAD

**Issue by fuddl** [chyingp/grunt-inline#55]
It seems its not supposed to work to inline images also from css properties like:
```css
<style>#foo { background-image: url('bar.jpg?__inline=true'); } ?>
```

Is that the case?
